"""
Integration test for the AMG preconditioner on an unstructured DISV (vertex)
grid generated by Voronoi tessellation.

Structured DIS grids give each cell a fixed number of neighbours (4 in 2D,
6 in 3D).  A DISV Voronoi grid is irregular: interior cells have 5-7 neighbours
(depending on seed-point density) and boundary cells have fewer.  This gives
the matrix variable row lengths and tests the AMG coarsening on an irregular
grid not covered by the DIS tests.

The model:
  - Single-layer (2D areal) confined GWF model; steady-state
  - Domain: 3,000 m (x) x 2,000 m (y)
  - Voronoi grid: 30 x 20 = 600 seed points → ~600 cells after boundary
    clipping; average cell diameter ≈ 100 m
  - K: checkerboard 5.0 / 0.5 m/d based on 100-m tile index of cell centre
  - CHD: west boundary cells (xc < 150 m) head=10 m;
         east boundary cells (xc > 2850 m) head=0 m
  - AMG hierarchy depth: ceil(log2(600/30)) = 5; PRECONDITIONER_LEVELS = 5
  - ILU reference: MILUT with PRECONDITIONER_LEVELS = 5

Two AMG configurations are tested against the MILUT reference (htol=1e-6 m):
  - disv_amg_cg   CG  + adaptive omega (RELAXATION_FACTOR 0; SPD system)
  - disv_amg_bgs  BiCGSTAB + fixed omega (RELAXATION_FACTOR 1)

The Voronoi grid is built using scipy.spatial.Voronoi + shapely for clipping;
no external Triangle or JMESH executable is required.
"""

from pathlib import Path

import flopy
import numpy as np
import pytest
from amg_test_utils import count_inner_iters
from framework import TestFramework

try:
    import scipy.spatial
    from shapely.geometry import Polygon
    from shapely.geometry import box as shapely_box

    HAS_VORONOI_DEPS = True
except ImportError:
    HAS_VORONOI_DEPS = False

paktest = "ims"
cmp_prefix = "mf6"

cases = [
    "disv_amg_cg",  # CG  + AMG + adaptive omega
    "disv_amg_bgs",  # BiCGSTAB + AMG + fixed omega
]
linear_accel = ["cg", "bicgstab"]
relax_factors = [0.0, 1.0]

# ---------------------------------------------------------------------------
# Domain and grid seed parameters
# ---------------------------------------------------------------------------

lx, ly = 3000.0, 2000.0  # domain dimensions (m)
nx_seeds, ny_seeds = 30, 20  # Voronoi seed points per axis
nlay = 1
top = 10.0
botm = [0.0]

chd_west_head = 10.0
chd_east_head = 0.0
chd_west_xmax = lx / nx_seeds * 1.5  # cells with centre x < this → west CHD
chd_east_xmin = lx - lx / nx_seeds * 1.5  # cells with centre x > this → east CHD

# K checkerboard tile size (m)
k_tile = lx / nx_seeds  # ≈ 100 m
k_hi, k_lo = 5.0, 0.5  # m/d

# AMG and ILU solver levels
amg_levels = 5
ilu_levels = 5

htol = 1.0e-6  # m; head tolerance for AMG-vs-ILU comparison


# ---------------------------------------------------------------------------
# Voronoi grid generator
# ---------------------------------------------------------------------------


def _build_voronoi_grid(nx, ny, lx, ly, seed=42):
    """Build a clipped Voronoi DISV grid for the rectangular domain [0,lx]x[0,ly].

    Uses mirror points on all four boundaries so that every interior Voronoi
    region is fully bounded before clipping.  Returns a dict suitable for
    unpacking into ModflowGwfdisv and parallel arrays xcell, ycell.
    """
    rng = np.random.default_rng(seed)

    dx = lx / nx
    dy = ly / ny

    # Regular seed grid with small jitter (5 % of cell size)
    xs = np.linspace(dx / 2, lx - dx / 2, nx)
    ys = np.linspace(dy / 2, ly - dy / 2, ny)
    xx, yy = np.meshgrid(xs, ys)
    pts = np.column_stack(
        [
            xx.ravel() + rng.uniform(-0.05 * dx, 0.05 * dx, nx * ny),
            yy.ravel() + rng.uniform(-0.05 * dy, 0.05 * dy, nx * ny),
        ]
    )

    # Mirror points to bound all regions
    mirror = np.vstack(
        [
            np.column_stack([-pts[:, 0], pts[:, 1]]),  # reflect x=0
            np.column_stack([2 * lx - pts[:, 0], pts[:, 1]]),  # reflect x=lx
            np.column_stack([pts[:, 0], -pts[:, 1]]),  # reflect y=0
            np.column_stack([pts[:, 0], 2 * ly - pts[:, 1]]),  # reflect y=ly
        ]
    )
    all_pts = np.vstack([pts, mirror])

    voronoi_tess = scipy.spatial.Voronoi(all_pts)
    domain = shapely_box(0.0, 0.0, lx, ly)

    vertices_dict = {}
    vertices_list = []

    def _vertex_id(x, y):
        key = (round(x * 1000), round(y * 1000))
        if key not in vertices_dict:
            vertices_dict[key] = len(vertices_list)
            vertices_list.append((x, y))
        return vertices_dict[key]

    cell2d = []
    xcell = []
    ycell = []

    for ic in range(len(pts)):
        region_idx = voronoi_tess.point_region[ic]
        region = voronoi_tess.regions[region_idx]
        if -1 in region or len(region) == 0:
            continue

        poly = Polygon(voronoi_tess.vertices[region])
        clipped = poly.intersection(domain)

        if clipped.is_empty or clipped.geom_type != "Polygon":
            continue

        coords = list(clipped.exterior.coords)[:-1]  # drop repeated closing pt
        icverts = [_vertex_id(x, y) for x, y in coords]
        xc = clipped.centroid.x
        yc = clipped.centroid.y

        cell2d.append([len(cell2d), xc, yc, len(icverts)] + icverts)
        xcell.append(xc)
        ycell.append(yc)

    vertices = [[iv, x, y] for iv, (x, y) in enumerate(vertices_list)]

    return (
        {
            "ncpl": len(cell2d),
            "nvert": len(vertices),
            "vertices": vertices,
            "cell2d": cell2d,
        },
        np.array(xcell),
        np.array(ycell),
    )


# ---------------------------------------------------------------------------
# Model-building helpers
# ---------------------------------------------------------------------------


def _build_gwf(sim, name, disv_props, xcell, ycell):
    """Add a steady-state confined GWF model on the Voronoi DISV grid."""
    gwf = flopy.mf6.ModflowGwf(sim, modelname=name, save_flows=True)

    flopy.mf6.ModflowGwfdisv(
        gwf,
        nlay=nlay,
        top=top,
        botm=botm,
        **disv_props,
    )

    flopy.mf6.ModflowGwfic(gwf, strt=(chd_west_head + chd_east_head) / 2.0)

    # Checkerboard K based on 100-m tile index of cell centre
    ncpl = disv_props["ncpl"]
    k_arr = np.empty((nlay, ncpl))
    tile_x = (xcell // k_tile).astype(int)
    tile_y = (ycell // k_tile).astype(int)
    k_arr[0, :] = np.where((tile_x + tile_y) % 2 == 0, k_hi, k_lo)
    flopy.mf6.ModflowGwfnpf(gwf, k=k_arr)

    spd_west = [
        [(0, ic), chd_west_head] for ic in range(ncpl) if xcell[ic] < chd_west_xmax
    ]
    spd_east = [
        [(0, ic), chd_east_head] for ic in range(ncpl) if xcell[ic] > chd_east_xmin
    ]
    flopy.mf6.modflow.ModflowGwfchd(gwf, stress_period_data=spd_west + spd_east)

    flopy.mf6.ModflowGwfoc(
        gwf,
        head_filerecord=f"{name}.hds",
        saverecord=[("HEAD", "ALL")],
    )
    return gwf


def _ims_kwargs(accel, relax, levels, name):
    return dict(
        print_option="SUMMARY",
        outer_dvclose=1.0e-8,
        outer_maximum=200,
        inner_dvclose=1.0e-12,
        inner_maximum=500,
        rcloserecord="1.0e-8 strict",
        linear_acceleration=accel,
        preconditioner_levels=levels,
        relaxation_factor=relax,
        filename=f"{name}.ims",
        csv_outer_output_filerecord=f"{name}_outer.csv",
    )


def _build_amg_sim(name, ws, accel, relax, disv_props, xcell, ycell):
    """Build a GWF simulation using the AMG preconditioner."""
    sim = flopy.mf6.MFSimulation(
        sim_name=name, version="mf6", exe_name="mf6", sim_ws=ws
    )
    flopy.mf6.ModflowTdis(sim, nper=1, perioddata=[(1.0, 1, 1.0)])
    ims = flopy.mf6.ModflowIms(
        sim,
        **_ims_kwargs(accel, relax, amg_levels, name),
        preconditioner_type="AMG",
    )
    gwf = _build_gwf(sim, name, disv_props, xcell, ycell)
    sim.register_ims_package(ims, [gwf.name])
    sim.write_simulation()
    return sim


def _build_ilu_sim(name, ws, accel, relax, disv_props, xcell, ycell):
    """Build a GWF simulation using the ILU preconditioner (reference)."""
    sim = flopy.mf6.MFSimulation(
        sim_name=name, version="mf6", exe_name="mf6", sim_ws=ws
    )
    flopy.mf6.ModflowTdis(sim, nper=1, perioddata=[(1.0, 1, 1.0)])
    ims = flopy.mf6.ModflowIms(sim, **_ims_kwargs(accel, relax, ilu_levels, name))
    gwf = _build_gwf(sim, name, disv_props, xcell, ycell)
    sim.register_ims_package(ims, [gwf.name])
    sim.write_simulation()
    return sim


# ---------------------------------------------------------------------------
# TestFramework interface
# ---------------------------------------------------------------------------


def build_models(idx, test):
    name = cases[idx]
    accel = linear_accel[idx]
    relax = relax_factors[idx]
    cmp_ws = Path(test.workspace) / cmp_prefix

    disv_props, xcell, ycell = _build_voronoi_grid(nx_seeds, ny_seeds, lx, ly, seed=42)

    amg_sim = _build_amg_sim(
        name, test.workspace, accel, relax, disv_props, xcell, ycell
    )
    ilu_sim = _build_ilu_sim(name, cmp_ws, accel, relax, disv_props, xcell, ycell)
    return amg_sim, ilu_sim


def check_output(idx, test):
    name = cases[idx]

    hds_amg = flopy.utils.HeadFile(Path(test.workspace) / f"{name}.hds").get_alldata()

    hds_ilu = flopy.utils.HeadFile(
        Path(test.workspace) / cmp_prefix / f"{name}.hds"
    ).get_alldata()

    assert hds_amg.shape == hds_ilu.shape, (
        f"Head array shapes differ: AMG {hds_amg.shape} vs ILU {hds_ilu.shape}"
    )

    max_diff = np.max(np.abs(hds_amg - hds_ilu))
    assert max_diff < htol, (
        f"AMG and ILU heads differ by {max_diff:.3e} m (tolerance {htol:.3e} m)"
    )

    # Iteration comparison only for the CG (SPD) case.  For the BiCGSTAB case
    # the confined steady-state Voronoi grid is small enough that ILUT can
    # compete on iteration count; the meaningful check is head agreement.
    if linear_accel[idx] == "cg":
        amg_iters = count_inner_iters(Path(test.workspace) / f"{name}_outer.csv")
        ilu_iters = count_inner_iters(
            Path(test.workspace) / cmp_prefix / f"{name}_outer.csv"
        )
        assert amg_iters < ilu_iters, (
            f"AMG total inner iterations ({amg_iters}) >= ILU ({ilu_iters})"
        )


@pytest.mark.skipif(
    not HAS_VORONOI_DEPS,
    reason="scipy and shapely are required for Voronoi grid generation",
)
@pytest.mark.parametrize("idx, name", enumerate(cases))
def test_mf6model(idx, name, function_tmpdir, targets):
    test = TestFramework(
        name=name,
        workspace=function_tmpdir,
        targets=targets,
        build=lambda t: build_models(idx, t),
        check=lambda t: check_output(idx, t),
        overwrite=False,
        compare=None,
    )
    test.run()
