name: MODFLOW 6 nightly build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.6.0
      with:
        auto-update-conda: true
        miniconda-version: "latest"
    - name: Install and print system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo ln -fs /usr/bin/gfortran-9 /usr/local/bin/gfortran
        gfortran --version
    - name: Install and print system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        gfortran --version
    - name: Install and print system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        gfortran --version
    - name: Install python packages
      run: |
        conda info
        conda install pip requests appdirs numpy matplotlib
        pip config --user set global.progress_bar off
        pip install https://github.com/modflowpy/flopy/zipball/develop
        pip install https://github.com/modflowpy/pymake/zipball/master
        pip install https://github.com/Deltares/amipy/zipball/master
    - name: Run t000_setup.py
      shell: bash -l {0}
      run: |
        cd autotest
        python test000_setup.py
        cd ..
