name: MODFLOW 6 nightly build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.3
      with:
        auto-update-conda: true
        miniconda-version: "latest"
    - run: conda --version
    - name: Install and print system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo ln -fs /usr/bin/gfortran-9 /usr/local/bin/gfortran
        gfortran --version
    - name: Install and print system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        gfortran --version
    - name: Install and print system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        gfortran --version
    - name: Install python packages
      run: |
        conda info
        conda install pip requests appdirs nose
        pip install numpy matplotlib
        pip install https://github.com/modflowpy/flopy/zipball/develop
        pip install https://github.com/modflowpy/pymake/zipball/master
        pip install https://github.com/Deltares/amipy/zipball/master
        python -c "import flopy; print('flopy: {}'.format(flopy.__version__))"
        python -c "import pymake; print('pymake: {}'.format(pymake.__version__))"
    - name: Build and zip applications
      run: |
        nosetests -v -w ./autotest build_nightly.py
        ls autotest/temp
